{% set version = "3.0.0b2.post2" %}

package:
    name: protobuf
    version: {{ version }}

source:
    fn: protobuf-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/p/protobuf/protobuf-{{ version }}.tar.gz
    md5: 42aa7ab79ebcb94917e938ff482ef7a6

build:
    number: 2

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - setuptools
        - six

test:
    imports:
        - google
        - google.protobuf
        - google.protobuf.compiler
        - google.protobuf.internal
        - google.protobuf.pyext

about:
    home: https://developers.google.com/protocol-buffers/
    license: New BSD License
    summary: 'Protocol Buffers'

extra:
    recipe-maintainers:
        - dopplershift
        - jakirkham
        - jjhelmus
        - ocefpaf
