{% set version = "3.0.0b2" %}
{% set version_str = "v3.0.0-beta-2" %}

package:
    name: protobuf
    version: {{ version }}

source:
    fn: protobuf_{{ version }}.tar.gz
    url: https://github.com/google/protobuf/archive/{{ version_str }}/protobuf-{{ version_str }}.tar.gz
    md5: e7f2602baffcbc27fb607de659cfbab6

build:
    number: 3
    skip: true  # [win]

requirements:
    build:
        - autoconf
        - automake
        - libtool
        - pkg-config
        - python
        - six
        - ordereddict        # [py26]
        - unittest2          # [py26]
        - git

    run:
        - python
        - six
        - ordereddict        # [py26]
        - unittest2          # [py26]

test:
    commands:
        - protoc --help
        - test -f ${PREFIX}/lib/libprotobuf.a                # [unix]
        - test -f ${PREFIX}/lib/libprotobuf.dylib            # [osx]
        - test -f ${PREFIX}/lib/libprotobuf.so               # [linux]

    imports:
        - google
        - google.protobuf
        - google.protobuf.internal
        - google.protobuf.pyext

about:
    home: https://developers.google.com/protocol-buffers/
    license: New BSD License
    summary: Protocol Buffers - Google's data interchange format

extra:
    recipe-maintainers:
        - dopplershift
        - jakirkham
        - jjhelmus
        - ocefpaf
