{% set name = "protobuf" %}
{% set version = "3.2.0" %}
{% set sha256 = "2a25c2b71c707c5552ec9afdfb22532a93a339e1ca5d38f163fe4107af08c54c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/google/protobuf/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # Skip the x64 Python 2.7 build on windows due to failing tests
  skip: True               # [win and py27 and x86_64]
  features:
    - vc9                # [win and py27]
    - vc10               # [win and py34]
    - vc14               # [win and py35]
    - vc14               # [win and py36]

requirements:
  build:
    - git
    - cmake              # [win]
    - autoconf           # [unix]
    - automake           # [unix]
    - libtool            # [unix]
    - pkg-config         # [unix]
    - zlib 1.2.*
    - python
    - setuptools
    - six
    - ordereddict        # [py26]
    - unittest2          # [py26]
  run:
    - zlib 1.2.*
    - python
    - setuptools
    - six
    - ordereddict        # [py26]
    - unittest2          # [py26]

test:
  commands:
    - protoc --help
    - test -f ${PREFIX}/lib/libprotobuf.a                           # [unix]
    - test -f ${PREFIX}/lib/libprotobuf.dylib                       # [osx]
    - test -f ${PREFIX}/lib/libprotobuf.so                          # [linux]
    - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1   # [win]
  imports:
    - google
    - google.protobuf
    - google.protobuf.internal
    - google.protobuf.pyext

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD 3-Clause
  summary: "Protocol Buffers - Google's data interchange format."

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - jjhelmus
    - ocefpaf
