travis:
  secure:
    BINSTAR_TOKEN: b8m2s3gaj6Te2MrWjgu9jdxw/PKSLYsqkQvZiLTdk+5rSqhgNLZVUAZVk4F2zxRhi06r0/eqD5XyuCY1oXBINb4MV9/xi3D8kKITKqMD07sGYiIjsroZ5LgrwIDTAThtxKGjjQze1D8P2wt39a9/bLnNYWPGbdtRQps6nqi2NckzyO/XyYawuenAn4s7mDRX9sUhLfUrzPysL2Vgw3B0LQD6MVyCbckWo1kYawhPbyQXBYFG30YBUlD2nHPm8AI1m3BnQ833lZ1P0TILihk49HfYgTY7Hx8BSSmBqDF5xlynovAUO+aRBN2JUM7Sf2ec3jMEodvPiLFv7N1NxMSonWuotnVsVjIpltk7Xf5R7fzhD6rbGfna6AaRcKE8/O6cb9nHSSz4jxtQ+ub1MS9dokImBzcY75WYljiaECugGyPuT6nliFeWNEF2dPS43ODuPWNxjlqqOdq3cZVwTUr2Joje76bpxqez1JF0CEyRZacsGakb81Jgsgz6EnTSOC2/Cv6WlTAcnHzfqRvp4scocAoA+RXuNWIqzXMF6fpIRPBZg1MiQ1j9krNv6ttO+cavr/dPLfaETBGepVMGp6nqS5IgBm21qMFXyLINqiJewhiuU6BA0LxRzPb9tSuM0I+dGZBk+2lWKW0Gyi/Bg3GLi/OLZNIPrHQ01+8poP93fCI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
