travis:
  secure:
    BINSTAR_TOKEN: t5j+RUs76HxUgeMdQ+sYLPQ82Tba1mF6PNtH/aoJ0wThlAf1Kwcow1lFtGk3czTlQuE5Vu4EFr5jjtk7t/lRAcEmLcrybn5YGwn66yVmIBC26u6qhBWPY+qVq+8PWb+wkOK7cCEQYMwurYmQX0iZgedRlZQtMxl1un3e8gStqIeY8Qyzz8uC6uyQqbqQ2jLq8n6Z0uBwQc0vjnWV43h1tBfpVuU1OZAQ9KIfl6c0u8UfNsgMF9zmyRRbCp63BUkFbjc84CneImYm79wmsPWxJ/P3AmjT8B5Q5RB9cBE3OB28vLDOTlM5ddY4KkjgiyyJFyR2OGH7Pb+s2vty5chpXx1lg7NubGyoSqaOQp2Tw0yuStXXpeqcKNbJCC522QFyUexehV6eEulI9V8c4BqYMq3ymtdPLttZJocox9BtrU69kh9p52cU9iMnCvAazTMYXyRBSuJcmXkry4o+ur99JFtaMG6IzwTr4bebt3sQqvOlVpHJOB6agLRa1cMhDwif2vnYm4SwYyaZ1Bpsz6VBMBEPe5J4iz3Txo97KzajGwmC8UgpOzItW90R/AqSET+HgACcIiBSj23+CgBgjGnmRpgjSQFpAC6j3f/Z39heRsaSf3YYm5AuwAvS4+T7a16iigs31Fnzrp0r0UHoauPD5sKkPKhSLZu7k21UK7quB2A=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
